image: stefankaestle/gcc

# Dependencies
# ------------------------------
#
# net-tools       for netstat, required in scripts/test_service.sh
#
# The rest is needed as described in the README.

before_script:
  - "apt-get update; apt-get install -y python-networkx python-pygraphviz libgv-python python-numpy python-pygraph python-matplotlib wget net-tools"
  - "(cd /usr/lib/python2.7/dist-packages; ln -s libgv_python27.x86_64-linux-gnu.so _gv.so)"
  - "apt-get install -y texlive-full"

stages:
  - test

basetest:
  stage: test
  artifacts:
    paths:
      - "simulator-server.log"
      - "visu/visu_gruyere_adaptivetree_atomic_broadcast.png"
  script:
    - scripts/test_service.sh
    - scripts/test_visu.sh
    - scripts/test_standalone.sh
