language: python
python:
    - 2.7
    - 3.5
    - 3.6
install:
    - travis_retry pip install coverage coveralls
    - travis_retry pip install -e ./core
    - travis_retry pip install -e ./dot
script:
    - coverage run tests/testrunner.py
notifications:
    email: false
after_success:
    - coveralls
